[netcdf]
repo = "/Users/daniele/Dropbox/Projects/startleiter/data/soundings"

[postgresql]
database = "startleiter"
username = "username"
password = "my-super-secure-password"
port = 5432
ip_address = "localhost"

# git ignore changes to this file: git update-index --skip-worktree startleiter/config/credentials.toml
# track again changes: git update-index --no-skip-worktree startleiter/config/credentials.toml