project:
  type: website

website:
  title: "Startleiter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - monitoring.qmd
      - statistics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



