name: Run Predictions

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

defaults:
  run:
    shell: bash -l {0}
jobs:
  extraction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/scrape.yaml
          cache-environment: true

      - name: Install startleiter
        working-directory: ${{github.workspace}}
        run: pip install -e .

      - name: Run predictions
        env:
          XCONTEST_USERNAME: ${{ secrets.XCONTEST_USERNAME }}
          XCONTEST_PASSWORD: ${{ secrets.XCONTEST_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # TODO: do not hardcode DATABASE_URL, use instead:
          # DATABASE_URL=$(heroku config:get DATABASE_URL -a startleiter) 
        working-directory: ${{github.workspace}}
        run: python startleiter/prediction.py
